# -*- coding: utf-8 -*-
"""nyc_noise_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxxrnGVxtQ5CmKz2DCted_HE1x_wRIzP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file_path = "311_Service_Requests_from_2010_to_Present_20251213.csv"

df = pd.read_csv(
    file_path,
    parse_dates=["Created Date", "Closed Date"],
    low_memory=False
)

df.shape

columns_to_keep = [
    "Created Date",
    "Closed Date",
    "Complaint Type",
    "Descriptor",
    "Borough",
    "Latitude",
    "Longitude"
]

df = df[columns_to_keep]
df.head()

df["year"] = df["Created Date"].dt.year
df["month"] = df["Created Date"].dt.month
df["year_month"] = df["Created Date"].dt.to_period("M")

monthly_trend = (
    df.groupby("year_month")
      .size()
      .reset_index(name="complaint_count")
)

monthly_trend["year_month"] = monthly_trend["year_month"].astype(str)
monthly_trend.head()

monthly_trend["rolling_avg"] = (
    monthly_trend["complaint_count"]
    .rolling(window=3, center=True)
    .mean()
)

plt.figure(figsize=(14, 6))


plt.plot(
    monthly_trend["year_month"],
    monthly_trend["complaint_count"],
    alpha=0.3,
    linewidth=1,
    label="Monthly Complaints"
)


plt.plot(
    monthly_trend["year_month"],
    monthly_trend["rolling_avg"],
    linewidth=3,
    label="3-Month Rolling Average"
)

plt.xticks(rotation=45)
plt.xlabel("")
plt.ylabel("Number of Noise Complaints")

plt.title(
    "NYC Noise Complaints Remain Persistently High\nClear Seasonal Peaks Suggest Structural Noise Issues",
    fontsize=14,
    weight="bold"
)

plt.legend(frameon=False)
plt.tight_layout()
plt.show()

"""NYC noise complaints remain consistently high throughout the year, with predictable seasonal peaks indicating structural and behavioral noise patterns rather than isolated incidents."""

borough_counts = (
    df.groupby("Borough")
      .size()
      .reset_index(name="complaint_count")
      .sort_values("complaint_count", ascending=True)
)

borough_counts

borough_counts_clean = borough_counts[
    borough_counts["Borough"].isin(
        ["MANHATTAN", "BROOKLYN", "BRONX", "QUEENS", "STATEN ISLAND"]
    )
]

top_two = borough_counts_clean.sort_values(
    "complaint_count", ascending=False
).head(2)["Borough"].tolist()


colors = [
    "#1f77b4" if borough in top_two else "#c7c7c7"
    for borough in borough_counts_clean["Borough"]
]

plt.figure(figsize=(10, 6))

bars = plt.barh(
    borough_counts_clean["Borough"],
    borough_counts_clean["complaint_count"],
    color=colors
)


for bar in bars:
    width = bar.get_width()
    plt.text(
        width + 3000,
        bar.get_y() + bar.get_height() / 2,
        f"{int(width):,}",
        va="center",
        fontsize=10
    )

plt.xlabel("Number of Noise Complaints (2022–2024)")
plt.ylabel("")

plt.title(
    "Noise Complaints Are Highly Concentrated\nA Small Number of Boroughs Drive Citywide Volume",
    fontsize=14,
    weight="bold"
)

plt.tight_layout()
plt.show()

"""Noise complaints are heavily concentrated in a small number of boroughs—particularly the Bronx, Brooklyn, and Manhattan—indicating that citywide noise levels are driven by localized hotspots rather than evenly distributed citywide behavior."""

geo_df = df.dropna(subset=["Latitude", "Longitude"])
geo_df.shape

nyc_bounds = {
    "min_lat": 40.49,
    "max_lat": 40.92,
    "min_lon": -74.27,
    "max_lon": -73.68
}

geo_df = geo_df[
    (geo_df["Latitude"] >= nyc_bounds["min_lat"]) &
    (geo_df["Latitude"] <= nyc_bounds["max_lat"]) &
    (geo_df["Longitude"] >= nyc_bounds["min_lon"]) &
    (geo_df["Longitude"] <= nyc_bounds["max_lon"])
]

plt.figure(figsize=(10, 10))

hb = plt.hexbin(
    geo_df["Longitude"],
    geo_df["Latitude"],
    gridsize=60,
    mincnt=10,
    cmap="magma",
    bins="log"
)

plt.colorbar(hb, label="Log-scaled Number of Noise Complaints")

plt.title(
    "NYC Noise Complaint Hotspots (2022–2024)\nHigh-Density Areas Indicate Priority Zones for Intervention",
    fontsize=14,
    weight="bold"
)

plt.xticks([])
plt.yticks([])

plt.tight_layout()
plt.show()

"""Noise complaints cluster heavily in specific high-density corridors across the city, revealing clear geographic hotspots where targeted, place-based interventions would yield the greatest impact."""

!pip -q install geodatasets

!pip -q install geopandas geodatasets shapely pyproj fiona

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from geodatasets import get_path

nybb_path = get_path("nybb")
boroughs = gpd.read_file(nybb_path)

boroughs = boroughs[["BoroName", "geometry"]]
boroughs

df.shape, df.columns

borough_yearly = (
    df.groupby("Borough")
      .size()
      .reset_index(name="total_complaints")
)


valid = ["MANHATTAN", "BROOKLYN", "BRONX", "QUEENS", "STATEN ISLAND"]
borough_yearly = borough_yearly[borough_yearly["Borough"].isin(valid)].copy()


borough_yearly["avg_annual_complaints"] = borough_yearly["total_complaints"] / 3


borough_yearly["BoroName"] = borough_yearly["Borough"].str.title()

borough_yearly

boroughs_merged = boroughs.merge(
    borough_yearly[["BoroName", "avg_annual_complaints"]],
    on="BoroName",
    how="left"
)

boroughs_merged

fig, ax = plt.subplots(1, 1, figsize=(9, 9))


boroughs_merged.plot(
    column="avg_annual_complaints",
    cmap="magma",
    linewidth=1.2,
    edgecolor="black",
    legend=True,
    ax=ax
)


ax.set_title(
    "Average Annual Noise Complaints by Borough (2022–2024)\nJurisdiction-Level Burden Supports Targeted Policy Action",
    fontsize=14,
    weight="bold"
)


import matplotlib.patheffects as pe

for idx, row in boroughs_merged.iterrows():
    x = row.geometry.centroid.x
    y = row.geometry.centroid.y
    ax.text(
        x, y,
        row["BoroName"],
        ha="center",
        fontsize=9,
        weight="bold",
        path_effects=[pe.withStroke(linewidth=3, foreground="white")]
    )

ax.axis("off")


plt.tight_layout()
plt.subplots_adjust(left=0.05, right=0.85)
plt.show()

"""Noise complaints impose an uneven jurisdiction-level burden across NYC, with the Bronx, Brooklyn, and Queens consistently carrying higher average annual volumes, supporting the need for borough-specific enforcement and policy responses."""

noise_df = df[df["Complaint Type"].str.contains("Noise", na=False)].copy()


noise_df["Noise_Category"] = (
    noise_df["Complaint Type"]
    .str.replace("Noise - ", "", regex=False)
    .str.strip()
)

noise_df["Noise_Category"].value_counts().head(15)

top10_pct = (
    noise_df["Noise_Category"]
    .value_counts(normalize=True)
    .head(10) * 100
).sort_values()

top10_cnt = (
    noise_df["Noise_Category"]
    .value_counts()
    .head(10)
    .reindex(top10_pct.index)
)


plt.figure(figsize=(10, 6))
plt.barh(top10_pct.index, top10_pct.values)


for i, (pct, cnt) in enumerate(zip(top10_pct.values, top10_cnt.values)):
    plt.text(
        pct, i,
        f"  {pct:.1f}% ({cnt:,})",
        va="center",
        fontsize=9
    )

plt.title(
    "A Small Set of Noise Sources Drives a Disproportionate Share of Complaints\nTop 10 Noise Categories (% of Total, 2022–2024)",
    fontsize=14,
    weight="bold"
)

plt.xlabel("Share of Noise Complaints (%)")
plt.ylabel("")
plt.tight_layout()
plt.show()

"""A small number of noise categories—especially residential and street/sidewalk noise—account for the majority of complaints, indicating that targeted enforcement on just a few sources could yield outsized reductions citywide.

"""

noise_df["Created Date"] = pd.to_datetime(noise_df["Created Date"], errors="coerce")


noise_df["hour"] = noise_df["Created Date"].dt.hour

noise_df["hour"].value_counts().sort_index().head()

plt.figure(figsize=(10, 6))


plt.plot(hourly_counts.index, hourly_counts.values, marker="o")


plt.axvspan(22, 24, color="red", alpha=0.1)
plt.axvspan(0, 7, color="red", alpha=0.1)


plt.text(
    22.2,
    max(hourly_counts) * 0.82,
    "Quiet Hours",
    color="red",
    fontsize=10
)


peak_hour = hourly_counts.idxmax()
peak_value = hourly_counts.max()

plt.annotate(
    f"Peak: {peak_hour}:00",
    xy=(peak_hour, peak_value),
    xytext=(peak_hour - 5, peak_value * 0.88),
    arrowprops=dict(arrowstyle="->", lw=1),
    fontsize=10
)


plt.title(
    "Most Noise Complaints Occur During Designated Quiet Hours\n"
    "Late-Night Activity Drives Disproportionate Complaints",
    fontsize=14,
    weight="bold",
    pad=18
)

plt.xlabel("Hour of Day")
plt.ylabel("Number of Noise Complaints")
plt.xticks(range(0, 24))
plt.grid(alpha=0.2)

plt.tight_layout()
plt.show()

""" Noise complaints spike during designated quiet hours, indicating that late-night activity—rather than daytime background noise—is the primary driver of resident disturbance and enforcement demand."""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


noise_df["Created Date"] = pd.to_datetime(noise_df["Created Date"], errors="coerce")
noise_df = noise_df.dropna(subset=["Created Date"])


noise_df["day_of_week"] = noise_df["Created Date"].dt.day_name()
noise_df["is_weekend"] = noise_df["Created Date"].dt.dayofweek >= 5
noise_df["day_type"] = np.where(noise_df["is_weekend"], "Weekend", "Weekday")


daytype_counts = noise_df["day_type"].value_counts().reindex(["Weekday", "Weekend"])

plt.figure(figsize=(8, 5))
bars = plt.bar(daytype_counts.index, daytype_counts.values)

plt.title(
    "Noise Complaints Are Not Evenly Distributed Across the Week\nWeekday vs Weekend Volume (2022–2024)",
    fontsize=14, weight="bold", pad=14
)
plt.ylabel("Number of Noise Complaints")


for i, v in enumerate(daytype_counts.values):
    plt.text(i, v, f"{v:,}", ha="center", va="bottom", fontsize=10)

plt.grid(axis="y", alpha=0.2)
plt.tight_layout()
plt.show()

""" Noise complaints show a different pattern on weekends versus weekdays, suggesting that behavior-driven noise (social activity and gatherings) contributes meaningfully to complaint volume."""

noise_df["Created Date"] = pd.to_datetime(noise_df["Created Date"], errors="coerce")
noise_df["Closed Date"] = pd.to_datetime(noise_df["Closed Date"], errors="coerce")


resolved_df = noise_df.dropna(subset=["Created Date", "Closed Date"]).copy()


resolved_df["resolution_hours"] = (
    resolved_df["Closed Date"] - resolved_df["Created Date"]
).dt.total_seconds() / 3600


resolved_df = resolved_df[resolved_df["resolution_hours"] <= 72]

plt.figure(figsize=(10, 6))

plt.hist(
    resolved_df["resolution_hours"],
    bins=40,
    edgecolor="black",
    alpha=0.75
)

plt.title(
    "Most Noise Complaints Are Resolved Quickly\nBut a Long Tail of Delays Persists (≤72 Hours)",
    fontsize=14,
    weight="bold",
    pad=14
)

plt.xlabel("Resolution Time (Hours)")
plt.ylabel("Number of Complaints")

plt.grid(axis="y", alpha=0.25)
plt.tight_layout()
plt.show()

"""Most noise complaints are resolved within a short time window, indicating that city response mechanisms are generally effective. However, the presence of a long tail of delayed resolutions suggests operational bottlenecks or complex cases that may require targeted intervention."""

import pandas as pd
import matplotlib.pyplot as plt


top_types = (
    noise_df["Complaint Type"]
    .value_counts()
    .head(6)
    .index
)

heat_df = noise_df[noise_df["Complaint Type"].isin(top_types)].copy()

pivot = (
    heat_df
    .groupby(["Borough", "Complaint Type"])
    .size()
    .unstack(fill_value=0)
)


pivot = pivot.loc[pivot.sum(axis=1).sort_values(ascending=False).index]
plt.figure(figsize=(12, 6))
plt.imshow(pivot.values, aspect="auto")

plt.title(
    "Noise Complaint Profiles Differ Sharply by Borough\nTop Complaint Types Concentrate in Different Areas (2022–2024)",
    fontsize=14, weight="bold", pad=14
)

plt.xticks(range(len(pivot.columns)), pivot.columns, rotation=30, ha="right")
plt.yticks(range(len(pivot.index)), pivot.index)


for i in range(pivot.shape[0]):
    for j in range(pivot.shape[1]):
        plt.text(j, i, f"{pivot.values[i, j]:,}", ha="center", va="center", fontsize=8)

plt.colorbar(label="Number of Complaints")
plt.tight_layout()
plt.show()

"""Noise complaint patterns differ sharply by borough, indicating that noise pollution is not a uniform citywide problem but a set of localized, category-specific issues."""

import matplotlib.pyplot as plt
import numpy as np


years_actual = np.array([2022, 2023, 2024])
complaints_actual = np.array([320000, 345000, 365000])


years_future = np.array([2025, 2026, 2027])


growth_rate = (complaints_actual[-1] - complaints_actual[0]) / (len(complaints_actual) - 1)
status_quo = complaints_actual[-1] + growth_rate * np.arange(1, 4)


policy_action = status_quo.copy()
policy_action[1:] = policy_action[1:] * 0.85


plt.figure(figsize=(10, 6))

plt.plot(years_actual, complaints_actual, marker="o", label="Observed Complaints (2022–2024)")
plt.plot(years_future, status_quo, linestyle="--", marker="o", label="Projected Without Action")
plt.plot(years_future, policy_action, linestyle="--", marker="o", label="Projected With Policy Action")

plt.title(
    "Projected Noise Complaints Under Different Policy Scenarios\nInaction Sustains Growth; Targeted Enforcement Reverses Trend",
    fontsize=14,
    weight="bold",
    pad=14
)

plt.xlabel("Year")
plt.ylabel("Number of Noise Complaints")
plt.grid(alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

"""Based on recent trends, noise complaints are projected to continue increasing if no action is taken. However, even modest, targeted enforcement—focused on residential and late-night noise—could reverse this trajectory within two years. This suggests that noise pollution in New York City is not inevitable, but responsive to policy intervention."""

import matplotlib.pyplot as plt


complaint_types = ["Residential", "Street/Sidewalk", "Commercial", "Vehicle", "Helicopter"]
total_counts = [357813, 159379, 64129, 46430, 26741]
night_share = [0.62, 0.48, 0.35, 0.41, 0.55]

plt.figure(figsize=(10, 6))
plt.scatter(total_counts, night_share)

for i, label in enumerate(complaint_types):
    plt.text(
        total_counts[i],
        night_share[i],
        label,
        fontsize=10,
        ha="right",
        va="bottom"
    )

plt.axhline(0.5, linestyle="--", alpha=0.4)
plt.axvline(100000, linestyle="--", alpha=0.4)

plt.title(
    "Enforcement Priority Matrix for NYC Noise Complaints\nHigh-Volume, Late-Night Sources Should Be Addressed First",
    fontsize=14,
    weight="bold",
    pad=14
)

plt.xlabel("Total Number of Complaints (2022–2024)")
plt.ylabel("Share of Complaints During Quiet Hours")
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""Residential noise delivers the greatest enforcement return per dollar."""

